# Generated by Django 3.2.14 on 2022-07-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlog',
            options={'get_latest_by': 'modified'},
        ),
    ]
