# Generated by Django 3.0.8 on 2020-07-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_site_reference_id', models.CharField(max_length=255)),
                ('measurement_site_reference_version', models.CharField(max_length=255)),
                ('measurement_site_name', models.CharField(max_length=255, null=True)),
                ('measurement_site_type', models.CharField(max_length=255)),
                ('length', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(max_length=255)),
                ('publication_reference_id', models.CharField(max_length=255)),
                ('publication_reference_version', models.CharField(max_length=255)),
                ('publication_time', models.DateTimeField()),
                ('measurement_start_time', models.DateTimeField()),
                ('measurement_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_type', models.CharField(max_length=255)),
                ('estimation_type', models.CharField(max_length=255)),
                ('travel_time', models.IntegerField()),
                ('traffic_speed', models.IntegerField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_lane', models.CharField(max_length=255)),
                ('vehicle_flow', models.IntegerField()),
                ('category_count', models.IntegerField()),
                ('category_type', models.CharField(max_length=255)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.Measurement')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.Publication'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('specific_lane', models.CharField(max_length=255)),
                ('camera_id', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lane_number', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('view_direction', models.IntegerField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255)),
                ('vehicle_category', models.CharField(max_length=255)),
                ('start_detection_time', models.DateTimeField()),
                ('end_detection_time', models.DateTimeField()),
                ('travel_time', models.IntegerField()),
                ('traffic_speed', models.IntegerField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.Measurement')),
            ],
        ),
    ]
