# Generated by Django 3.1 on 2020-08-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0002_auto_20200812_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficflow',
            name='category_count',
        ),
        migrations.RemoveField(
            model_name='trafficflow',
            name='category_type',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('traffic_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.trafficflow')),
            ],
        ),
    ]
