# Generated by Django 3.1 on 2020-08-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0003_auto_20200812_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrafficFlow',
            new_name='MeasuredFlow',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='traffic_flow',
            new_name='measured_flow',
        ),
    ]
