# Generated by Django 3.1 on 2020-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0004_auto_20200812_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltime',
            name='data_quality',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='estimation_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
