# Generated by Django 3.1 on 2020-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0005_auto_20200812_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
