# Generated by Django 3.2.8 on 2021-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0006_auto_20200813_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtraveltime',
            name='end_detection_time',
            field=models.DateTimeField(blank=True, help_text='The date time the vehicle was detected at the end lcoation of the measurement site (section) in UTC format.', null=True),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='start_detection_time',
            field=models.DateTimeField(blank=True, help_text='The date time the vehicle was detected at the start location of the measurement site (section) in UTC format.', null=True),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='traffic_speed',
            field=models.IntegerField(help_text='The computed driving speed in kmph.'),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='travel_time',
            field=models.IntegerField(help_text='The computed travel time in seconds.'),
        ),
        migrations.AlterField(
            model_name='lane',
            name='specific_lane',
            field=models.CharField(help_text='Indicative name for the lane (lane1, lane2, lane3 … lane9 etc) used in the Amsterdam Travel Time system. The actual lane number is available at Camera.lane_number with respect to the camera view direction at the measurement location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='index',
            field=models.IntegerField(help_text="The index attribute indicates the order of measurement location in the measurement site. Optional, if the measurement site is of type 'location'", null=True),
        ),
        migrations.AlterField(
            model_name='measuredflow',
            name='specific_lane',
            field=models.CharField(help_text='Indicative name for the lane (lane1, lane2, lane3 … lane9 etc) used in the Amsterdam Travel Time system. See Lane.specific_lane.', max_length=255),
        ),
        migrations.AlterField(
            model_name='measuredflow',
            name='vehicle_flow',
            field=models.IntegerField(help_text='Provides the total number of vehicle detections at the measurement site (location) for the measurement period.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='measurement_end_time',
            field=models.DateTimeField(help_text='The time recorded here is the ending time of the supply period in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='measurement_start_time',
            field=models.DateTimeField(help_text='The time recorded here is the starting time of the supply period in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_reference_id',
            field=models.CharField(help_text='Unique publication identifier. The ID is a unique for data set delivered by the system and shall remain unchanged throughout the system lifetime', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_reference_version',
            field=models.CharField(help_text='The version of the publication. Incremented (+1) every time section and/or route definition are modified i.e., a) New section(s) and/or trajectory(ies) are activated, b) Existing section(s) and/or trajectory(ies) are deactivated c)\tExisting section(s) and/or trajectories are modified', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_time',
            field=models.DateTimeField(help_text="The date time the latest version (refer attribute 'version') for this publication was published in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(help_text='The type of publication. One of: TrafficFlow, TravelTime, IndividualTravelTime', max_length=255),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='data_quality',
            field=models.FloatField(help_text='Quality of the computed travel time/speed (0...100%)', null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='estimation_type',
            field=models.CharField(help_text='The type of estimation used, one of best, estimated, instantaneous, reconstituted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='traffic_speed',
            field=models.IntegerField(help_text='The computed driving speed in kmph.'),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time',
            field=models.IntegerField(help_text='The computed travel time in seconds.'),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time_type',
            field=models.CharField(help_text='One of: raw, representative, processed, predicted, actual', max_length=255),
        ),
    ]
