# Generated by Django 3.1.7 on 2021-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0006_auto_20200813_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='measurement_duration',
            field=models.IntegerField(help_text='The duration element provides the measurement frequency at which the travel time values are calculated/exported.', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='measurement_end_time',
            field=models.DateTimeField(help_text='The time recorded here is the ending time of the supply period in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='measurement_start_time',
            field=models.DateTimeField(help_text='The time recorded here is the starting time of the supply period in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_reference_id',
            field=models.CharField(help_text='Unique publication identifier. The ID is a unique for data set delivered by the system and shall remain unchanged throughout the system lifetime', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_reference_version',
            field=models.CharField(help_text='The version of the publication. Incremented (+1) every time section and/or route definition are modified i.e., a) New section(s) and/or trajectory(ies) are activated, b) Existing section(s) and/or trajectory(ies) are deactivated c)\tExisting section(s) and/or trajectories are modified', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_time',
            field=models.DateTimeField(help_text="The date time the latest version (refer attribute 'version') for this publication was published in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(help_text='The type of publication. One of: TrafficFlow, TravelTime, IndividualTravelTime', max_length=255),
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_reference_id',
            new_name='reference_id',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_reference_version',
            new_name='version',
        ),
    ]
