# Generated by Django 3.1 on 2020-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0006_auto_20200813_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lane',
            name='camera_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='lane',
            name='lane_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lane',
            name='specific_lane',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='lane',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lane',
            name='view_direction',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='index',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measuredflow',
            name='specific_lane',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='measuredflow',
            name='vehicle_flow',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='length',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_site_reference_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_site_reference_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_site_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='data_quality',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='estimation_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='traffic_speed',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time_type',
            field=models.CharField(max_length=20),
        ),
    ]
