# Generated by Django 3.2.8 on 2021-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0007_add_help_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasuredFlow',
            new_name='TrafficFlow',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='TrafficFlowCategoryCount',
        ),
        migrations.RenameField(
            model_name='trafficflowcategorycount',
            old_name='measured_flow',
            new_name='traffic_flow',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_reference_id',
            new_name='reference_id',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_reference_version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='traveltime',
            old_name='travel_time_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_site_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_site_reference_id',
            new_name='reference_id',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_site_reference_version',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_site_type',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='end_detection_time',
            new_name='detection_end_time',
        ),
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='start_detection_time',
            new_name='detection_start_time',
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='MeasurementLocation',
        ),
        migrations.RenameField(
            model_name='lane',
            old_name='location',
            new_name='measurement_location',
        ),
    ]
