# Generated by Django 3.1.7 on 2021-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0007_auto_20210415_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltime',
            name='data_error',
            field=models.BooleanField(default=False, help_text='Optional elemnt to indicate whether there were errors in the travel time computation or there are alarm reported against this site.', max_length=255),
        ),

        migrations.AddField(
            model_name='traveltime',
            name='num_input_values_used',
            field=models.IntegerField(
                help_text='The total no: of samples (individual travel times) used to compute the travel time.',
                null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='data_quality',
            field=models.FloatField(help_text='Quality of the computed travel time/speed (0...100%)', null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='estimation_type',
            field=models.CharField(help_text='The type of estimation used, one of best, estimated, instantaneous, reconstituted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='traffic_speed',
            field=models.IntegerField(help_text='The computed driving speed in kmph.'),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time',
            field=models.IntegerField(help_text='The computed travel time in seconds.'),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='travel_time_type',
            field=models.CharField(help_text='One of: raw, representative, processed, predicted, actual', max_length=255),
        ),
        migrations.RenameField(
            model_name='traveltime',
            old_name='travel_time_type',
            new_name='type',
        ),
    ]
