# Generated by Django 3.2.8 on 2021-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0008_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='measurement_duration',
            field=models.IntegerField(help_text='The duration element provides the measurement frequency at which the travel time values are calculated/exported.', null=True),
        ),
        migrations.AddField(
            model_name='traveltime',
            name='data_error',
            field=models.BooleanField(default=False, help_text='Optional elemnt to indicate whether there were errors in the travel time computation or there are alarm reported against this site.', max_length=255),
        ),
        migrations.AddField(
            model_name='traveltime',
            name='num_input_values_used',
            field=models.IntegerField(help_text='The total no: of samples (individual travel times) used to compute the travel time.', null=True),
        ),
    ]
