# Generated by Django 3.2.8 on 2021-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0008_rename_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='version',
            new_name='_type',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='type',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='_type',
            new_name='type',
        ),
    ]
