# Generated by Django 3.1.7 on 2021-04-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0009_vehiclecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='vehicle_category',
            new_name='old_vehicle_category',
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='end_detection_time',
            field=models.DateTimeField(blank=True, help_text='The date time the vehicle was detected at the end lcoation of the measurement site (section) in UTC format.', null=True),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='start_detection_time',
            field=models.DateTimeField(blank=True, help_text='The date time the vehicle was detected at the start location of the measurement site (section) in UTC format.', null=True),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='traffic_speed',
            field=models.IntegerField(help_text='The computed driving speed in kmph.'),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='travel_time',
            field=models.IntegerField(help_text='The computed travel time in seconds.'),
        ),
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='end_detection_time',
            new_name='detection_end_time',
        ),
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='start_detection_time',
            new_name='detection_start_time',
        ),
        migrations.AddField(
            model_name='individualtraveltime',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, help_text='The vehicle category. Reference: https://www.rdw.nl/zakelijk/paginas/nationale-kleine-serie-typegoedkeuring', null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.vehiclecategory'),
        ),
    ]
