# Generated by Django 3.2.8 on 2021-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0009_add_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='individualtraveltime',
            old_name='vehicle_category',
            new_name='old_vehicle_category',
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='old_vehicle_category',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='individualtraveltime',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, help_text='The vehicle category. Reference: https://www.rdw.nl/zakelijk/paginas/nationale-kleine-serie-typegoedkeuring', null=True, on_delete=models.deletion.CASCADE, to='reistijden_v1.vehiclecategory'),
        ),
    ]
