# Generated by Django 3.2.8 on 2021-10-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0010_01_individual_travel_time_vehicle_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='The measurementsitereference element describes the measurement site (section or trajectory) against which the values are reported', max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(help_text='An optional readable name for the measurement site.', max_length=255, null=True)),
                ('type', models.CharField(help_text='\n        Measurement site type. A measurement site can be either a location, a section\n        or a trajectory.\n        - Location\n        A location refers to a point location in the road network from which data\n        (vehicle passages) are collected.  A location consists of one or more\n        camera-lane pairs. The Amsterdam Travel time system delivers vehicle count\n        per location per lane per vehicle category under the trafficflow publication.\n        - Section\n        A section refers to a traversible route between two locations.\n        The Amsterdam Travel time system delivers the following for the sections\n        defined in the system:\n        a. Raw, representative and processed travel time values under the traveltime\n           publication.\n        b. Individual travel time values under the individualtraveltime publication\n        - Trajectory\n        A trajectory refers to a traversible route created using one or more sections.\n        The Amsterdam Travel time system delivers the following for the trajectories\n        defined in the system:\n        a. Processed, predicted and actual under the traveltime publication.\n        ', max_length=255)),
                ('length', models.IntegerField(help_text='This element contains information about the length (in meters) of the measurement site. Applicable only for sections and trajectories', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reistijden_v1.measurementsite'),
        ),
    ]
