# Generated by Django 3.2 on 2021-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0010_auto_20210415_1357'),
    ]

    operations = [
    ]
