# Generated by Django 3.2.14 on 2022-07-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0010_measurement_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLocation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text="The index attribute indicates the order of measurement location in the measurement site. Optional, if the measurement site is of type 'location'", null=True)),
                ('measurement_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurementsite')),
            ],
        ),
        migrations.CreateModel(
            name='Lane2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_lane', models.CharField(help_text='Indicative name for the lane (lane1, lane2, lane3 … lane9 etc) used in the Amsterdam Travel Time system. The actual lane number is available at Camera.lane_number with respect to the camera view direction at the measurement location.', max_length=255)),
                ('measurement_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurementlocation2')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='The unique camera identifier (defined by the ANPR data supplier). Format: UUIDv4', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lane_number', models.IntegerField(help_text="Lanenumber, calculated from the 'middle' of the road. Lane direction is indicated by being - positive (regular traffic should be moving away from the camera), or - negative (regular traffic should be moving towards the camera).  For example: - Left lane with regular traffic moving away from the camera is number: 1 - Left lane with regular traffic moving towards the camera is number: -1Rechts v/d middenberg positief (verkeer dat van je af gaat)Links negatief (verkeer dat naar je toe komt)")),
                ('status', models.CharField(help_text='On, off or outage. On: camera is active for travel-time system and functioning, Off: camera is not active for travel-time system, Outage: camera is active for travel-time system, but malfunctioning', max_length=255, null=True)),
                ('view_direction', models.IntegerField(help_text='The direction the camera is looking in, expressed in degrees. 0 and every 22,5 degrees are valid values. 0 equals looking North,  180 degrees equals to South, 90 degrees to East, 270 degrees to West.')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.lane2')),
            ],
        ),
    ]
