# Generated by Django 3.2 on 2021-04-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0011_auto_20210419_1228'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='individualtraveltime',
        #     name='old_vehicle_category',
        # ),
    ]
