# Generated by Django 3.2.14 on 2022-08-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0011_camera_lane2_measurementlocation2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='individualtraveltime',
            name='old_vehicle_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trafficflowcategorycount',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trafficflowcategorycount',
            name='vehicle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='individualtraveltime',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, help_text='The vehicle category. Reference: https://www.rdw.nl/zakelijk/paginas/nationale-kleine-serie-typegoedkeuring', null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.vehiclecategory'),
        ),
    ]
