# Generated by Django 3.2.14 on 2022-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0011_camera_lane2_measurementlocation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltime',
            name='data_error',
            field=models.BooleanField(null=True, help_text='Optional element to indicate whether there were errors in the travel time computation or there are alarm reported against this site.', max_length=255),
        ),
        migrations.AddField(
            model_name='traveltime',
            name='num_input_values_used',
            field=models.IntegerField(help_text='The total no: of samples (individual travel times) used to compute the travel time.', null=True),
        ),
    ]
