# Generated by Django 3.2.8 on 2021-10-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0012_03_traffic_flow_category_count_vehicle_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementlocation',
            name='measurement_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurementsite'),
        ),
        migrations.AlterField(
            model_name='measurementlocation',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurement'),
        ),
    ]
