# Generated by Django 3.1.7 on 2021-04-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0013_measurementsite'),
    ]

    operations = [
    ]
