# Generated by Django 3.2.14 on 2022-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0013_travel_time_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='measurement_duration',
            field=models.IntegerField(help_text='The duration element provides the measurement frequency at which the travel time values are calculated/exported.', null=True),
        ),
    ]
