# Generated by Django 3.1.7 on 2021-04-19 14:16

from django.db import migrations


def create_measurement_sites(apps, schema_editor):
    MeasurementSite = apps.get_model('reistijden_v1', 'MeasurementSite')
    Measurement = apps.get_model('reistijden_v1', 'Measurement')

    unique_measurement_sites = Measurement.objects.values_list(
        'measurement_site_reference_id',
        'measurement_site_reference_version',
        'measurement_site_name',
        'measurement_site_type',
        'length'
    ).distinct()

    for measurement_site in unique_measurement_sites:
        measurement_site, _ = MeasurementSite.objects.get_or_create(
            reference_id=measurement_site[0],
            version=measurement_site[1],
            name=measurement_site[2],
            type=measurement_site[3],
            length=measurement_site[4]
        )

        Measurement.objects.filter(
            measurement_site=None,
            measurement_site_reference_id=measurement_site[0],
            measurement_site_reference_version=measurement_site[1],
            measurement_site_name=measurement_site[2],
            measurement_site_type=measurement_site[3],
            length=measurement_site[4],
        ).update(measurement_site=measurement_site)


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0013_measurementsite'),
    ]

    operations = [
        migrations.RunPython(create_measurement_sites),
    ]
