# Generated by Django 3.2.14 on 2022-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0014_05_cameras_from_lanes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsite',
            name='locations_json',
            field=models.JSONField(help_text='This field is made to include a nested json object containing the locations, its lanes and its respective cameras. If something changes in the measurement site or any of the locations, lanes or cameras, new records need to be created for all of them. To be able to test this somewhat easily, we create a json object in this field to be able to test for changes in any of those objects by doing a select on all fields of the measurement site, including this locations_json. Note that the order of keys in the json objects does not matter when using a native jsonb field.', null=True),
        ),
    ]
