# Generated by Django 3.2.14 on 2022-08-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0014_alter_fk_references_to_new_measurement_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='MeasurementOld',
        ),
        migrations.RenameModel(
            old_name='Lane',
            new_name='LaneOld',
        ),
        migrations.RenameModel(
            old_name='MeasurementLocation',
            new_name='MeasurementLocationOld',
        ),
    ]
