# Generated by Django 3.1.7 on 2021-04-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0014_auto_20210419_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='length',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_site_name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_site_reference_id',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_site_reference_version',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_site_type',
        ),
    ]
