# Generated by Django 3.2.14 on 2022-08-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0014_measurementsite_first_publication_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtraveltime',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurement2'),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurement2'),
        ),
        migrations.AlterField(
            model_name='traveltime',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.measurement2'),
        ),
    ]
