# Generated by Django 3.2 on 2021-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0015_auto_20210422_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasuredFlow',
            new_name='TrafficFlow',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='measured_flow',
            new_name='traffic_flow',
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='specific_lane',
            field=models.CharField(help_text='Indicative name for the lane (lane1, lane2, lane3 … lane9 etc) used in the Amsterdam Travel Time system. See Lane.specific_lane.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='vehicle_flow',
            field=models.IntegerField(help_text='Provides the total number of vehicle detections at the measurement site (location) for the measurement period.'),
        ),
    ]
