# Generated by Django 3.2 on 2021-04-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0016_auto_20210422_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TrafficFlowCategoryCount',
        ),
        migrations.AddField(
            model_name='trafficflowcategorycount',
            name='vehicle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reistijden_v1.vehiclecategory'),
        ),
    ]
