# Generated by Django 3.2.14 on 2022-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0016_rename_old_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lane2',
            new_name='Lane',
        ),
        migrations.RenameModel(
            old_name='Measurement2',
            new_name='Measurement',
        ),
        migrations.RenameModel(
            old_name='MeasurementLocation2',
            new_name='MeasurementLocation',
        ),
    ]
