# Generated by Django 3.2 on 2021-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0017_rename_category_trafficflowcategorycount'),
    ]

    operations = [
    ]
