# Generated by Django 3.2.14 on 2022-08-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0018_rename_sequences_constraints_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementlocationold',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='measurementold',
            name='publication',
        ),
        migrations.DeleteModel(
            name='LaneOld',
        ),
        migrations.DeleteModel(
            name='MeasurementLocationOld',
        ),
        migrations.DeleteModel(
            name='MeasurementOld',
        ),
    ]
