# Generated by Django 3.2 on 2021-04-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0018_auto_20210429_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficflowcategorycount',
            name='type',
        ),
    ]
