# Generated by Django 3.2.14 on 2022-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0019_cleanup_old_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='measurement_start_time',
            field=models.DateTimeField(db_index=True, help_text='The time recorded here is the starting time of the supply period in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]'),
        ),
    ]
