# Generated by Django 3.2.14 on 2022-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0019_cleanup_old_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_time',
            field=models.DateTimeField(db_index=True, help_text="The date time the latest version (refer attribute 'version') for this publication was published in UTC format: ISO 8601 [https://en.wikipedia.org/wiki/ISO_8601]"),
        ),
    ]
