# Generated by Django 3.2.14 on 2022-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0020_alter_publication_measurement_start_time'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE FUNCTION measurements_in_range(timestamp, timestamp) RETURNS SETOF reistijden_v1_measurement AS '
SELECT  m.*
FROM    reistijden_v1_measurement AS m
JOIN    reistijden_v1_publication p ON m.publication_id = p.id
WHERE 1=1
    AND m.publication_id BETWEEN
        (SELECT min(id) FROM reistijden_v1_publication WHERE measurement_start_time >= $1)
        AND
        (SELECT max(id) FROM reistijden_v1_publication WHERE measurement_start_time < $2)
    AND p.measurement_start_time between $1 and $2
' LANGUAGE SQL;
            """
            ,reverse_sql="""
DROP FUNCTION IF EXISTS measurements_in_range;
            """
        ),
    ]
