# Generated by Django 3.2 on 2021-04-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0021_auto_20210429_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementlocation',
            name='measurement',
        ),
    ]
