# Generated by Django 3.2 on 2021-04-29 12:55

from django.db import migrations


def update_cameras(apps, schema_editor):
    Camera = apps.get_model('reistijden_v1', 'Camera')
    Lane = apps.get_model('reistijden_v1', 'Lane')

    unique_cameras = Lane.objects.values_list(
        'id',
        'camera_id',
        'latitude',
        'longitude',
        'lane_number',
        'status',
        'view_direction'
    ).distinct()

    for camera in unique_cameras:
        Camera.objects.create(
            lane_id=camera[0],
            reference_id=camera[1],
            latitude=camera[2],
            longitude=camera[3],
            lane_number=camera[4],
            status=camera[5],
            view_direction=camera[6]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0023_camera'),
    ]

    operations = [
        migrations.RunPython(update_cameras)
    ]
