# Generated by Django 3.2 on 2021-04-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reistijden_v1', '0023_camera'),
    ]

    operations = [
    ]
