# Generated by Django 2.2.7 on 2019-12-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VlogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField()),
                ('vri_id', models.IntegerField()),
                ('raw', models.CharField(max_length=255)),
            ],
        ),
    ]
